// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/mazrean/todoList/common"
	"github.com/mazrean/todoList/handler/v1"
	"github.com/mazrean/todoList/repository"
	"github.com/mazrean/todoList/repository/sqlx"
	"github.com/mazrean/todoList/service"
	v1_2 "github.com/mazrean/todoList/service/v1"
)

// Injectors from wire.go:

func InjectAPI(config *Config) (*v1.API, error) {
	addr := config.Addr
	sessionKey := config.SessionKey
	sessionSecret := config.SessionSecret
	session := v1.NewSession(sessionKey, sessionSecret)
	context := v1.NewContext()
	db, err := sqlx.NewDB()
	if err != nil {
		return nil, err
	}
	dashboard := sqlx.NewDashboard(db)
	taskStatus := sqlx.NewTaskStatus(db)
	task := sqlx.NewTask(db)
	v1Dashboard := v1_2.NewDashboard(db, dashboard, taskStatus, task)
	v1TaskStatus := v1_2.NewTaskStatus(db, dashboard, taskStatus)
	v1Task := v1_2.NewTask(db, dashboard, taskStatus, task)
	middleware := v1.NewMiddleware(context, session, v1Dashboard, v1TaskStatus, v1Task)
	user := sqlx.NewUser(db)
	authorization := v1_2.NewAuthorization(db, user)
	v1User := v1.NewUser(context, session, authorization)
	dashboard2 := v1.NewDashboard(context, session, v1Dashboard)
	taskStatus2 := v1.NewTaskStatus(context, session, v1TaskStatus)
	task2 := v1.NewTask(context, session, v1Task)
	api := v1.NewAPI(addr, session, middleware, v1User, dashboard2, taskStatus2, task2)
	return api, nil
}

// wire.go:

type Config struct {
	Addr          common.Addr
	SessionKey    common.SessionKey
	SessionSecret common.SessionSecret
}

var (
	addrField          = wire.FieldsOf(new(*Config), "Addr")
	sessionKeyField    = wire.FieldsOf(new(*Config), "SessionKey")
	sessionSecretField = wire.FieldsOf(new(*Config), "SessionSecret")

	dbBind                   = wire.Bind(new(repository.DB), new(*sqlx.DB))
	userRepositoryBind       = wire.Bind(new(repository.User), new(*sqlx.User))
	dashboardRepositoryBind  = wire.Bind(new(repository.Dashboard), new(*sqlx.Dashboard))
	taskStatusRepositoryBind = wire.Bind(new(repository.TaskStatus), new(*sqlx.TaskStatus))
	taskRepositoryBind       = wire.Bind(new(repository.Task), new(*sqlx.Task))

	authorizationServiceBind = wire.Bind(new(service.Authorization), new(*v1_2.Authorization))
	dashboardServiceBind     = wire.Bind(new(service.Dashboard), new(*v1_2.Dashboard))
	taskStatusServiceBind    = wire.Bind(new(service.TaskStatus), new(*v1_2.TaskStatus))
	taskServiceBind          = wire.Bind(new(service.Task), new(*v1_2.Task))
)
